name: PChologram
version: ${project.version}
main: net.pcampus.pchologram.PChologram
api-version: '1.13'
authors: [PcampusNetwork, Garfieldcmix]
description: This is holo plugin for Pcmapus Network
website: www.pcampus.net
commands:
  pcholo:
    description: holo command